siteTitle="Gatsby Starter Site"
linkPrefix = "/gatsby-starter-default"

[hero]
title = "Title"
subtitle = "Subtitle"

[footer]
title = "Footer"
text = """
Footer text
"""

[letter]
text = """
Dear Mum, Dad, Grandma, and everyone else looking to vote leave,

We’re writing this letter to you to implore you not to.

The choice to leave the EU will have severe consequences on myself and the people we love. From forcing us to leave the places we call home, to reducing what little assets we have even further, this is not going to help us. 

We so often come to you for advice - you have more wisdom and experience than we do on so many matters, and you usually know what’s best for us, but on this occasion we’re begging you to please listen to us instead and vote with us to remain. We know you mean well - you think of the past and want to provide us with the best future - but voting Leave will result in anything but.

There are so few plans in place if we leave. This isn’t like going to a party without planning how you’ll get home later, it’s a drastic decision that will impact our country and our people for decades, and making that choice with almost no idea of what we’ll do next is foolish, especially considering that rejoining is likely to be very hard. Should we really make bets on such an uncertainty? This is a situation for being 100% sure, not for relying on ‘gut feelings’.

The current Leave EU movement brings to mind Trump’s rise to political power. It’s based on the promise of a better life with no facts on how we’re going to get it. It’s using blatant lies to exploit your fears. It’s blaming other people for our problems. There are plenty of legitimate issues that need addressing in the UK, but most of them have nothing to do with the EU, and scapegoating them is only going to add to our problems, not relieve them. 

We understand that it can be hard to separate the truth from the lies, especially when our media is so willing to write biased propaganda and sell it as ‘news’, but we’ve put this site together to try and make that easier. 

Maybe this will change your mind, maybe it won’t, but we hope that you’ll read it, and that you’ll bear these facts and our opinions in mind when you place your vote on Thursday.

Thank you.

Signed…
"""

[goodies]
text = "Here are a few that strongly believe the UK should remain a member of the EU"
people = [
  { title = "Mark Carney", d = "Governor of the Bank of England" },
  { title = "International Monetary Fund" },
  { title = "Institute for Fiscal Studies" },
  { title = "Confederation of British Industry" },
  { title = "Leaders/heads of state of every single other member of the EU" },
  { title = "Barack Obama", d = "President of the United States of America" },
  { title = "Eight former US Treasury Secretaries" },
  { title = "Xi Jinping", d = "President of China" },
  { title = "Pranab Mukherjee", d = "Prime Minister of India" },
  { title = "Justin Trudeau", d = "Prime Minister of Canada" },
  { title = "Tony Abbott", d = "Prime Minister of Australia" },
  { title = "Shinzō Abe", d = "Prime Minister of Japan" },
  { title = "John Key", d = "Prime Minister of New Zealand" },
  { title = "The chief executives of most of the top 100 companies in the UK including Marks and Spencer, BT, Asda, Vodafone, Virgin, IBM, BMW etc." },
  { title = "Kofi Annan", d = "the former Secretary General of the United Nations" },
  { title = "All living former Prime Ministers of the UK (from both parties)" },
  { title = "Virtually all reputable and recognised economists" },
  { title = "The Prime Minister of the UK" },
  { title = "The leader of the Labour Party" },
  { title = "The Leader of the Liberal Democrats" },
  { title = "The Leader of the Green Party" },
  { title = "The Leader of the Scottish National Party" },
  { title = "The leader of Plaid Cymru" },
  { title = "Martin Lewis", d = "that money saving dude off the telly" },
  { title = "The Secretary General of the TUC" },
  { title = "Oxford University" },
  { title = "Cambridge University" },
  { title = "Unison" },
  { title = "National Union of Students" },
  { title = "National Union of Farmers" },
  { title = "Stephen Hawking" },
  { title = "Chief Executive of the NHS" },
  { title = "300 of the most prominent international historians" },
  { title = "Director of Europol" },
  { title = "David Anderson QC", d = "Independent Reviewer of Terrorism Legislation" },
  { title = "Former Directors of GCHQ" },
  { title = "Secretary General of Nato" },
  { title = "Church of England" },
  { title = "Church in Scotland" },
  { title = "Church in Wales" },
  { title = "Friends of the Earth" },
  { title = "Greenpeace" },
  { title = "Director General of the World Trade Organisation" },
  { title = "WWF" },
  { title = "World Bank" },
  { title = "OECD " }
]

[baddies]
text = "Here are pretty much the only notable people who think we should leave the EU"
people = [
  { title = "Boris Johnson", d = "who probably doesn’t really care either way, but knows he’ll become Prime Minister if the country votes to leave" },
  { title = "Iain Duncan Smith", d = "A former Secretary of State for Work and Pensions who carried out a brutal regime of cuts to benefits and essential support for the poorest in society as well as the disabled and sick" },
  { title = "Michael Gove", d = "That idiot that was Education Secretary and every single teacher in the country hated with a furious passion for the damage he was doing to the education system" },
  { title = "Nigel Farage", d = "Leader of UKIP" },
  { title = "BNP" },
  { title = "Britain First" },
  { title = "Donald Trump" },
  { title = "Keith Chegwin" },
  { title = "David Icke" }
]
